[workspace]
resolver = "3"
members = ["crates/metafix-cli", "crates/metafix-core"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Aleksandr Sokolov <alex@sokolov.dev>"]
readme = "README.md"
repository = "https://github.com/aOri69/metafix.git"
homepage = "https://github.com/aOri69/metafix.git"
keywords = [
    "exif",
    "metadata",
    "photo",
    "cli",
    "batch",
    "google-takeout"
]
categories = [
    "command-line-utilities",
    "multimedia",
    "data-processing",
    "file-management"
]

[workspace.dependencies]
thiserror = { version = "2.0.12" }
anyhow = { version = "1.0.98" }
tempfile = {version = "3.20.0"}
pretty_assertions = "1.4.1"
rstest = "0.25.0"
fs_extra = "1.3.0"